### PR TITLE
Upgrade to React 16/Enzyme 3/Jest 22

### PR DESCRIPTION
**Pull request by schneidmaster**
* Upgrade packages
* Update tests to account for enzyme breaking changes in 2 -> 3, e.g. [changed children behaviour](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#children-now-has-slightly-different-meaning)

### CODE REVIEW

**Comment by schneidmaster** [comment]
Hey @ggingell -- could you have a look at this when you get a minute? Trying to kill off the last react 16 peerDependency warning in my application 🙂

**Review by ggingell — APPROVED** [review]
Looks great! Thank you :)

**Comment by ggingell** [comment]
Published under v2.5.0. Thanks again @schneidmaster

**Comment by schneidmaster** [comment]
Thanks @ggingell!

**Pull request merged**
